### PR TITLE
add a service based on ldproxy

### PR DESCRIPTION
**Pull request by pvgenuchten**
@justb4 can you verify on this PR if it is a valid approach to add an additional service, i have not been able to test locally (expect for the docker-compose itself). Let me know your thoughts. Thanx

### CODE REVIEW

**Review by justb4 — CHANGES_REQUESTED** [review]
Quick feedback:
- merge recent changes on `main` branch, including README.md
- think the ldproxy data/config dir is missing as it is referred in `docker-compose.yml`
- if there is a lot of data, not fit for GitHub we need other data strategy
- portmapping: all requests go through Traefik, think only 7080 needs exposure
- the service needs to be added to services/start.sh/stop.sh
- need to update the deploy.yml (need to add fine-grained deploy later)
-  don't know if ldproxy can work on a subpath automatically (for pygeoapi we needed to add SCRIPT_PATH).

But in general this is a workable approach! Mainly details to be filled in.

**Comment by pvgenuchten** [comment]
> think the ldproxy data/config dir is missing as it is referred in docker-compose.yml

For now i have no data yet, so the data dir is created but empty (i used manual configuration to set up a wfs backend)

> if there is a lot of data, not fit for GitHub we need other data strategy

What do you think about these options:
- download it from its original location (once at volume creation)
- reference a remote postgres database

> portmapping: all requests go through Traefik, think only 7080 needs exposure

ok

> the service needs to be added to services/start.sh/stop.sh

Sure? I noticed:

```
SERVICES="$(find ${SCRIPT_DIR} -maxdepth 1 -mindepth 1)"
for SERVICE in ${SERVICES} do	
pushd ${SERVICE}		
./start.sh
```

> need to update the deploy.yml (need to add fine-grained deploy later)

ok

> don't know if ldproxy can work on a subpath automatically (for pygeoapi we needed to add SCRIPT_PATH).

Me neither, i can ask or we can find out

**Comment by justb4** [comment]
> > think the ldproxy data/config dir is missing as it is referred in docker-compose.yml
> 
> For now i have no data yet, so the data dir is created but empty (i used manual configuration to set up a wfs backend)
ok let's start with WFS-only
> 
> > if there is a lot of data, not fit for GitHub we need other data strategy
> 
> What do you think about these options:
> 
> * download it from its original location (once at volume creation)
> * reference a remote postgres database
See issue #10 
> 
> > portmapping: all requests go through Traefik, think only 7080 needs exposure
> 
> ok
> 
> > the service needs to be added to services/start.sh/stop.sh
> 
> Sure? I noticed:
> 
> ```
> SERVICES="$(find ${SCRIPT_DIR} -maxdepth 1 -mindepth 1)"
> for SERVICE in ${SERVICES} do	
> pushd ${SERVICE}		
> ./start.sh
> ```
Yes, I just added that, so this does not apply anymore!
> 
> > need to update the deploy.yml (need to add fine-grained deploy later)
> 
> ok
See issue #9 
> 
> > don't know if ldproxy can work on a subpath automatically (for pygeoapi we needed to add SCRIPT_PATH).
> 
> Me neither, i can ask or we can find out
Yes this is always an issue, possibly on their Gitter or maybe that is in documentation.

If I fixed the Traefik config correctly you can now also run the stack locally, e.g. on MacOSX Docker Desktop.
* call services/start.sh
* go to http://localhost:8000/pygeoapi_test (did not use 80 as usually something else running there).

**Comment by justb4** [comment]
Running ldproxy on URL with Subpath: https://github.com/interactive-instruments/ldproxy/blob/master/docs/de/configuration/global-configuration.md#external-url 
Though this does not work locally.

**Comment by pvgenuchten** [comment]
do you get an error from ldproxy?
i will try to run locally

**Comment by justb4** [comment]
@pvgenuchten 

* did you also merge-in the latest changes for docs? so http://localhost:8000 shows the doc page? 
* can you access ldproxy with a local port mapping (without Traefik), e.g. in docker-compose.yml

```
    ports:
      - 7180:7080
    expose:
      - 7080
```
and try http://localhost:7180/rest/services ?

* What could also be the case is that ldproxy listens on localhost/127.0.0.1. If possible you need to change the listen-address to `0.0.0.0`. But I see no config option for that.

**Pull request merged**
